name: MacOS package build

on:
  workflow_dispatch:

jobs:
  build_package_macos:
    name: Build macOS nuget packages
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make input folder
      run: mkdir lib/MacOS/input
    - name: Build native libraries
      run: sh ./../buildNativeLibs.sh ${GITHUB_WORKSPACE}/lib ${GITHUB_WORKSPACE}/lib/MacOS/output
      working-directory: lib/MacOS/input
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build ./lib/MacOS/LibMtpSharp.Native.MacOS.WithDependencies/LibMtpSharp.Native.MacOS.WithDependencies.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: macos_packages
        path: ./lib/packages/LibMtpSharp.Native.MacOS.*.nupkg
  test_package_macos:
    name: Test macOS nuget packages
    runs-on: macos-latest
    needs: build_package_macos
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Download MacOS packages
      uses: actions/download-artifact@v2
      with:
        name: macos_packages
        path: ./lib/packages/
    - name: Run test
      run: dotnet run --project ./test/LibMtpSharp.Native.Test.MacOS/LibMtpSharp.Native.Test.MacOS.csproj